---
- name: "Register all repo files"
  ansible.builtin.find:
    paths: /sysroot/etc/yum.repos.d/
    pattern: "*.repo"
  register: minimalinstall__repos
  tags: repos

- name: "Change path for gpg-keys" # Red Hat Bugzilla – Bug 2247326
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: '(^gpgkey=file://)(.*$)'
    replace: '\1/sysroot\2'
  loop: "{{ minimalinstall__repos.files }}"

#- name: "Install minimal OS"
#  ansible.builtin.dnf:
#    name: "{{ distributionminimalpackages }}"
#    #name: '@Minimal Install'
#    state: present
#    installroot: '/sysroot'
#    releasever: "{{ installdistribution['version'] }}"

- name: "Install minimal OS"
  ansible.builtin.command: "dnf --releasever {{ installdistribution['version'] }} --assumeyes --installroot=/sysroot install {% for item in distributionminimalpackages %} {{ item | quote }} {% endfor %}"
  register: minimalinstall__minimalinstall
  changed_when: minimalinstall__minimalinstall.rc == 0
  failed_when: minimalinstall__minimalinstall.rc != 0
  tags: installtry

- name: "Change back path for gpg-keys" # Red Hat Bugzilla – Bug 2247326
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: '(^gpgkey=file://)/sysroot(.*$)'
    replace: '\1\2'
  loop: "{{ minimalinstall__repos.files }}"
  tags: repotry

- name: "Resolve relocated rpmdb" # https://fedoraproject.org/wiki/Changes/RelocateRPMToUsr
  #For install of older distributions this shouldn't be done actually... Still need to solve this.
  ansible.builtin.shell:
    cmd: '[ -d rpm ]&&mv rpm{,.bak}&&ln -s /usr/lib/sysimage/rpm ./'
  args:
    chdir: /sysroot/var/lib
