---
- name: resolve install urls
  geertsky.bambini.generate_minimal_install_urls_info:
    distribution: "{{ distribution }}" 
  register: result
  debugger: on_failed

- name: "Install minimal OS"
  ansible.builtin.command: "rpm --root=/sysroot --install {{ result.rpm_urls }}"
  register: minimalinstall__minimalinstall
  changed_when: minimalinstall__minimalinstall.rc == 0
  failed_when: minimalinstall__minimalinstall.rc != 0
  tags: installtry

#- name: "Change back path for gpg-keys" # Red Hat Bugzilla – Bug 2247326
#  ansible.builtin.replace:
#    path: "{{ item.path }}"
#    regexp: '(^gpgkey=file://)/sysroot(.*$)'
#    replace: '\1\2'
#  loop: "{{ minimalinstall__repos.files }}"
#  tags: repotry

- name: "Resolve relocated rpmdb" # https://fedoraproject.org/wiki/Changes/RelocateRPMToUsr
  ansible.builtin.shell:
    cmd: 'rpmdb --root=/sysroot --exportdb|chroot /sysroot rpmdb --importdb'
