---
- name: "Trigger continuation of boot process"
  ansible.builtin.file:
    path: "/tmp/ansible-finished"
    state: touch
    mode: '0644'

- name: Clear gathered facts from all currently targeted hosts
  ansible.builtin.meta: clear_facts
