distributionreporpms: 
  - files/rpms/rocky/8/
distributionminimalpackages:
  - '@Minimal Install'
  - 'kernel'
  - 'grub2-common'
  - 'grub2-tools'
  - 'grub2-tools-efi'
  - 'grub2-tools-extra'
  - 'grub2-pc'
  - 'grub2-pc-modules'
  - 'grub2-efi-ia32'
  - 'grub2-efi-ia32-cdboot'
  - 'grub2-efi-ia32-modules'
  - 'grub2-efi-x64'
  - 'grub2-efi-x64-cdboot'
  - 'grub2-efi-x64-modules'
  - 'grub2-tools'
  - 'grub2-tools-efi'
  - 'grub2-tools-extra'
  - 'grub2-tools-minimal'
  - 'grub2-efi-ia32-cdboot'
  - 'shim-x64'
  - 'lvm2'
  - 'setup'
  - 'efibootmgr'
  - 'python3'

installdisk: /dev/vda
